format_version: 10
pipelines:
  volume-driver-ci:
    group: driverGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-b3e173b:
        git: https://github.com/t1d333/docker-volume-ftp-driver
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
            timeout: 0
            tasks:
            - exec:
                command: ls
                run_if: passed
    - lint-and-test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-lint:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - '123'
                command: echo
                run_if: passed
          run-tests:
            timeout: 0
            tasks:
            - exec:
                command: echo "test"
                run_if: passed
    - deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          upload:
            timeout: 0
            tasks:
            - exec:
                command: echo 123
                run_if: passed

