// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StateManager is an autogenerated mock type for the StateManager type
type StateManager struct {
	mock.Mock
}

// SaveState provides a mock function with given fields:
func (_m *StateManager) SaveState() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SyncState provides a mock function with given fields:
func (_m *StateManager) SyncState() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStateManager creates a new instance of StateManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateManager {
	mock := &StateManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
