// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/t1d333/docker-volume-ftp-driver/internal/models"
)

// FTPManager is an autogenerated mock type for the FTPManager type
type FTPManager struct {
	mock.Mock
}

// CheckConnection provides a mock function with given fields: opt
func (_m *FTPManager) CheckConnection(opt *models.FTPConnectionOpt) error {
	ret := _m.Called(opt)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.FTPConnectionOpt) error); ok {
		r0 = rf(opt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFTPManager creates a new instance of FTPManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFTPManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *FTPManager {
	mock := &FTPManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
